version: '3'
services:
  hellodjango:
    build: ./hellodjango
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    ports:
      - 127.0.0.1:8000:8000
    restart: always
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    restart: always
