apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellodjango-deployment
  labels:
    app: hellodjango
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellodjango
  template:
    metadata:
      labels:
        app: hellodjango
    spec:
      containers:
        - name: hellodjango
          image: textninja/hellodjango:latest
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_DB
              value: django
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: password
          ports:
            - containerPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_DB
              value: django
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: password
          ports:
            - containerPort: 5432
